version: 2.1

# The following stanza defines a map named defaults with a variable that may be
# inserted using the YAML merge (<<: *) key later in the file to save some
# typing. See http://yaml.org/type/merge.html for details.
defaults: &defaults
  docker:
    - image: circleci/node:12

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Run Lint Suite
          command: |
            ./lint-shell-scripts.sh
  test-python:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Unit Test Python
          command: |
            git ls-files | grep -E '^tests/.*\.py$' | xargs python3 -m unittest

  release:
    <<: *defaults
    steps:
      - checkout
      - run: npx --quiet semantic-release

workflows:
  version: 2
  main:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - lint
      - test-python
      - release:
          context: reaction-publish-semantic-release
          requires:
            - lint
            - test-python
          filters:
            branches:
              only: trunk
